development:
  adapter: postgresql
  encoding: unicode
  database: library_management_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: library_management_test
  pool: 5

production:
  url: <%= ENV['DATABASE_URL'] %>
